# permissions for end users to view aliases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mailu-operator
    app.kubernetes.io/managed-by: kustomize
  name: alias-viewer-role
rules:
- apiGroups:
  - operator.mailu.io
  resources:
  - aliases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.mailu.io
  resources:
  - aliases/status
  verbs:
  - get
