# permissions for end users to edit domains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mailu-operator
    app.kubernetes.io/managed-by: kustomize
  name: domain-editor-role
rules:
- apiGroups:
  - operator.mailu.io
  resources:
  - domains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.mailu.io
  resources:
  - domains/status
  verbs:
  - get
