name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: ~1.22

jobs:
  build:
    name: Build operator image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Build
        run: make docker-build IMG=drpsychick/mailu-operator:latest

  publish:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    name: Build and publish operator image
    runs-on: ubuntu-latest
    needs: build
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
    permissions:
      contents: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: OCI Metadata for multi-arch image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            drpsychick/mailu-operator
          tags: |
            type=sha
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: make buildx-build IMG=drpsychick/mailu-operator:${{ steps.meta.outputs.version }} VERSION=${{ steps.meta.outputs.version }}

      - name: Build operator install manifest
        env:
          RELEASE_VERSION: ${{ steps.meta.outputs.version }}
        run: |
          make build-installer IMG=drpsychick/mailu-operator:${{ steps.meta.outputs.version }} VERSION=${{ steps.meta.outputs.version }}

      - name: Commit operator install manifest
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'dist/*.yaml'

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/install.yaml
          generate_release_notes: true
