name: Publish

on:
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:
  publish:
    name: Build and publish operator image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
    permissions:
      contents: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4 # golang-version:go
          check-latest: true

      - name: OCI Metadata for multi-arch image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            drpsychick/mailu-operator
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # pushes a) "main" or b) $TAG+"latest"
      - name: Build and push
        env:
          VERSION: ${{ steps.meta.outputs.version }}
        run: make docker-buildx

# main branch must contain the latest install.yaml already with the right tag ("main" or $TAG)
#      - name: Build operator install manifest
#        env:
#          VERSION: ${{ steps.meta.outputs.version }}
#        run: |
#          make build-installer
#
#      - name: Commit operator install manifest
#        uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          file_pattern: 'dist/*.yaml'

# release-please will take care of tagging
#      # pushing a tag will trigger this
#      - name: Release
#        uses: softprops/action-gh-release@v2
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          generate_release_notes: true
