---
name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
      releases_info: ${{ toJSON(steps.release.outputs) }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          # to create PRs and trigger GitHub workflows, requires a PAT
          token: ${{ secrets.PAT_GITHUB_TOKEN }}

      - run: echo $JSON
        name: Release Please Output Info
        env:
          JSON: ${{ toJSON(steps.release.outputs) }}
